### ISSUE TITLE
Autoload in composer.json

### ISSUE THREAD

**Issue by stdex** [akrabat/slim-bookshelf#1]
I think it's bad idea use full path to Bookshelf dir in composer autoload, because if someone wants to add some functional it can be very confusing.
https://github.com/akrabat/slim-bookshelf/blob/master/composer.json#L19

**Comment by akrabat** [comment]
I don't understand. What would suggest instead?

**Comment by stdex** [comment]
> "App\": "app/src"

**Comment by akrabat** [comment]
I disagree. The namespace I'm autoloading is `Bookshelf`. I don't have an `App` namespace.
